version: '3.8'

services:
  auth:
    build: .
    ports:
      - "4001:4001"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://shared-mongo:27017/mychat
      - REDIS_URL=redis:6379
      - JWT_SECRET=your-super-secret-key
    depends_on:
      - redis
    networks:
      - mychat-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mychat-net

networks:
  mychat-net:
    external: true
