version: "3.8"

services:
  auth:
    build: .
    ports:
      - "4001:4001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mychat
    depends_on:
      - mongo
    networks:
      - mychat-net

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mychat-net

volumes:
  mongo-data: {}  # <--- ต้องประกาศตรงนี้ด้วย

networks:
  mychat-net:
    external: true
