services:
  auth:
    build: .
    ports:
      - "4001:4001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mychat
      - REDIS_URL=redis:6379
      - JWT_SECRET=your-super-secret-key
    depends_on:
      - mongo
      - redis
    networks:
      - mychat-net

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mychat-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mychat-net

volumes:
  mongo-data: {}

networks:
  mychat-net:
    external: true
